### ISSUE TITLE
Blocking Read

### ISSUE THREAD

**Issue by phillipCouto** [jonhoo/bus#1]
Great library!!!! Simple yet effecient! I am just curious for the sake of completion why not implement the blocking read the same way you demonstrate it in your example?

I know it may not be ideal but atleast it will be feature complete and you can optimize in the future. Plus it will make the example more concise and easier to follow for new users.

Just a suggestion =)

**Comment by jonhoo** [comment]
The solution using `thread::yield_now` isn't great in terms of performance, and it wastes a lot of CPU cycles. I've implemented it properly now, where receiver threads are parked when trying to receive on an empty bus. This comes at a slight cost to writes, as they now need to check whether there are any threads to wake up before they can return.

**Comment by phillipCouto** [comment]
Like I said it was just to make the API symmetrical or more complete to the end user and could be optimized later on if time wasn't permitting. Anyway glad to see you were able to put in place a more efficient method to start with =)

Thanks!

**Comment by jonhoo** [comment]
Yeah, I got that, I'm just hesitant to put out those kinds of things, because then people will start complaining that it's inefficient :p I'm still not entirely happy with the current solution, because it won't do very well in very high-churn situations. I'd like to adopt something like https://github.com/mvdnes/spin-rs/issues/29 to busy-wait and yield a few times before resorting to a thread park (there are `TODO`s in the code already), but that's for another day.
