### ISSUE TITLE
Option for a resizing bus

### ISSUE THREAD

**Issue by LaylConway** [jonhoo/bus#10]
I'm using bus to broadcast events from a business logic model, which later get consumed by views. This happens in a synchronous application loop. Currently if the bus' buffer is exceeded this will result in either a crash or a hang depending on if I use `try_broadcast().unwrap()` or `broadcast()`. If possible I would rather have an option for performance and memory to degrade instead, avoiding a crash.

**Comment by jonhoo** [comment]
It's an interesting idea, but unfortunately what you're asking will be very difficult to implement without adding locking back in, which would decrease overall performance significantly (in all cases, not just when dynamically resizing). That said, I'm curious about why you want this particular feature? The situation you describe suggests that you have a sender that is faster than your receiver(s), and in that case there is no queue length that will "save" you. In fact, as the system keeps running, you will eventually run out of memory, since the queue will grow without bound. In general, *something* in your system has to either block or drop work to mitigate this problem; boundless queues are only a stopgap measure.

**Comment by LaylConway** [comment]
My sender isn't faster than my receivers, they're running on the same thread. I'm using bus to decouple systems by using it as a way to broadcast events to listeners. There's just a possibility where the sender hits the limit if there's many events during a frame before the receivers are handled.

**Comment by jonhoo** [comment]
Ah, I see. If you're doing everything in a single thread then I think I'd recommend just keeping a `VecDeque` per listener, and simply pushing the event onto all the queues whenever you receive one instead. That gives you the resizing behavior you want, it will be faster because it doesn't require atomics, and your code may even be somewhat simplified :)

**Comment by LaylConway** [comment]
I'll take a look at that, thanks
