### ISSUE TITLE
How do I use a bus with two threads?

### ISSUE THREAD

**Issue by brunoqc** [jonhoo/bus#6]
I'm new with Rust. This could be could more about using Rust than bus.

Is it possible with Arc? or would bus need to implement the 'sync' trait? (I don't really know about that trait).

Note that I don't want to do `bus.add_rx()` on the line after `Bus::new(10)` since in my case it would be done at runtime (when a network connection is opened).

```rust
extern crate bus;
use std::{thread, time};
use bus::Bus;

fn main() {
    let mut bus = Bus::new(10);

    thread::spawn(move || {
        let mut i = 0;
        loop {
            bus.broadcast(format!("{}", i));
            i += 1;
            thread::sleep(time::Duration::from_secs(1));
        }        
    });

    loop {
        let mut rx1 = bus.add_rx();
        let r = rx1.recv();
        println!("<- {}", r.unwrap());
    }
}
```

**Comment by jonhoo** [comment]
@brunoqc welcome to Rust! From the use-case you show here, it seems like you should instead use a [regular Rust channel](https://doc.rust-lang.org/std/sync/mpsc/fn.channel.html). Bus is specifically for when you need *multiple* threads to receive every transmission. In your code above, this is not necessary.

Now, you are hitting on an important limitation of Bus. You need exclusive access to a bus in order to add a receiver, **and** you need exclusive access to it in order to broadcast on it. Ideally, I would change Bus such that you could `.clone()` a receiver, but this is fairly hard to implement correctly given Bus' architecture. The solution for your particular scenario would be to use a [`Mutex`](https://doc.rust-lang.org/std/sync/struct.Mutex.html) wrapped in an [`Arc`](https://doc.rust-lang.org/std/sync/struct.Arc.html):

```rust
extern crate bus;
use std::{thread, time};
use std::sync::{Arc,Mutex};
use bus::Bus;

fn main() {
    let bus = Arc::new(Mutex::new(Bus::new(10)));

    let also_bus = bus.clone();
    thread::spawn(move || {
        let mut i = 0;
        loop {
            also_bus.lock().unwrap().broadcast(format!("{}", i));
            i += 1;
            thread::sleep(time::Duration::from_secs(1));
        }        
    });

    loop {
        let mut rx1 = bus.lock().unwrap().add_rx();
        let r = rx1.recv();
        println!("<- {}", r.unwrap());
    }
}
```

Note this code **can** deadlock. Broadcast can block waiting for a receiver (while holding the bus lock), but the bottom loop is waiting for the lock in order to add a receiver, and thus isn't draining the bus. To get around this, you'd probably need to use `try_broadcast` instead, and release the lock and retry if it fails because the bus is full.

**Comment by brunoqc** [comment]
> welcome to Rust!

Thanks!!

> In your code above, this is not necessary.

My code was an exemple. I would like to use bus to send data to multiples websocket connections.

While waiting for your reply I found out about `Arc::new(Mutex::new(bus))` and I saw `try_broadcast`. Thanks for explaining and telling me how bus behaves.

In the last loop, do you need the lock while waiting for `revc()`? Could you do something like (I'm assuming the mutex unlocks before the loop (but I may be missing something, I had to use `drop()` in my code)):

```rust
let mut rx1;
{
    rx1 = bus.lock().unwrap().add_rx();
}
loop {
    let r = rx1.recv();
    println!("<- {}", r.unwrap());
}
```

**Comment by jonhoo** [comment]
No, you only need the lock to create the receiver. The receiver itself is "disconnected" from the bus, and can be received on without having exclusive access (or access at all) to the bus. The code you give above should work fine, though I don't think you need the extra scope:

```rust
let mut rx1 = bus.lock().unwrap().add_rx();
loop {
    let r = rx1.recv();
    println!("<- {}", r.unwrap());
}
```

For this particular code, you could also use the `into_iter` method:

```rust
let mut rx1 = bus.lock().unwrap().add_rx();
for r in rx1.into_iter() {
    println!("<- {}", r);
}
```

**Comment by brunoqc** [comment]
Thanks!
